cat docker-compose.yml       


services:

  mkcert:

    environment:

      - domain=*.home.com,*.site.com,*.local.com

    container_name: mkcert

    volumes:

        - ./certs/:/root/.local/share/mkcert

    image: vishnunair/docker-mkcert

    labels:

      - "traefik.enable=false"

    networks:

      - web


  traefik:

    image: traefik:latest

    container_name: traefik

    ports:

      - "80:80"

      - "443:443"

      - "8080:8080"

    volumes:

      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"

      - "./config/dynamic.yml:/etc/traefik/dynamic.yml:ro"

      - "./certs/:/etc/certs:ro"

    labels:

      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`traefik.home.com`)"

      - "traefik.http.routers.traefik.entrypoints=https"

      - "traefik.http.routers.traefik.tls=true"

      - "traefik.http.routers.traefik.service=traefik@docker"

      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

    networks:

      - web


  portainer:

    image: portainer/portainer-ce:latest

    container_name: portainer

    restart: always

    security_opt:

      - no-new-privileges:true

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock:ro

      - portainer_data:/data

    labels:

      - "traefik.enable=true"

      - "traefik.http.routers.portainer.rule=Host(`portainer.home.com`)"

      - "traefik.http.routers.portainer.entrypoints=https"

      - "traefik.http.routers.portainer.tls=true"

      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

    networks:

      - web


  mariadb:

    image: mariadb:latest

    container_name: mariadb

    restart: unless-stopped

    environment:

      - MYSQL_ROOT_PASSWORD=password_here
      # Optionally add more environment variables:
      # - MYSQL_DATABASE=your_database
      # - MYSQL_USER=your_user
      # - MYSQL_PASSWORD=your_password

    volumes:

      - mariadb_data:/var/lib/mysql

    networks:

      - web


  phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: phpmyadmin

    environment:

      - PMA_ARBITRARY=1

      - PMA_HOST=mariadb

    restart: unless-stopped

    volumes:

      - ./darkwolf/:/var/www/html/themes/darkwolf/

    networks:

      - web

    labels:

      - "traefik.enable=true"

      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.home.com`)"

      - "traefik.http.routers.phpmyadmin.entrypoints=https"

      - "traefik.http.routers.phpmyadmin.tls=true"

      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"


networks:

  web:

    external: true


volumes:

  portainer_data:

  mariadb_data:
